$(document).ready(function() {
    $("#image1").click(function(){
        $("#description-service1").show()
        $("#image1").hide()
    });
    $("#description-service1").click(function(){
        $("#image1").show()
        $("#description-service1").hide()
    })
    $("#image2").click(function(){
        $("#description-service2").show()
        $("#image2").hide()
    });
    $("#description-service2").click(function(){
        $("#image2").show()
        $("#description-service2").hide()
    })
    $("#image3").click(function(){
        $("#description-service3").show()
        $("#image3").hide()
    });
    $("#description-service3").click(function(){
        $("#image3").show()
        $("#description-service3").hide()
    })
})